# Generated by Django 3.0.5 on 2020-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200513_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('AN', 'Anonim'), ('US', 'User'), ('MO', 'Moderator'), ('AD', 'Administrator'), ('DD', 'Administrator Django')], default='AN', max_length=2),
        ),
    ]
